### ISSUE TITLE
Invalid route name, already in use: 'rapporteur_engine'

### ISSUE THREAD

**Issue by sshaw** [envylabs/rapporteur#13]
Using Rails 4.1.

Normally one would mount the engine in their routes file like so:

```rb
mount Rapporteur::Engine => "/foo"
```

But this gem [attempts to do that itself](https://github.com/envylabs/rapporteur/blob/82fc0586ac7799079fc60c581557948fffac2fe6/config/routes.rb#L11). When the two are combined the above error is raised. 

Really I would not automount.  I think most engines don't.

**Comment by nbibler** [comment]
This sounds like it's related to #8.

I agree with both that it's probably better to explicitly mount the endpoint… I'll try to take a look back at these two concerns when I have a chance.

In the meantime, perhaps the approach taken in the pull request might help you?

**Comment by sshaw** [comment]
> This sounds like it's related to #8...

Somewhat. But I think #8 is not needed. 

> In the meantime, perhaps the approach taken in the pull request might help you?

#8 has 2 issues: 1) Rack app is not necessary, [an engine is a rack app](http://api.rubyonrails.org/classes/Rails/Engine.html#method-i-call) 2) all you need to do is remove [these lines](https://github.com/envylabs/rapporteur/blob/82fc0586ac7799079fc60c581557948fffac2fe6/config/routes.rb#L10-L20) from routes.rb and 💥 problem solved.
This will also fix #7. As the `/status.:format` route that's being added not doesn't work anyways. 

Given this there should be no compatibility concern...

**Comment by nbibler** [comment]
The compatibility concern is that developers will have to change the way they configure (mount) the status route. Since you can just `bundle update` and have it work… it'll have to be a new major release with instructions to `mount Rapporteur::Engine, at: '/status'` in your application's `config/routes.rb`.

I took a stab at reworking the library a little bit to rely more heavily on namespaced Engines and require users to mount the Engine as described above.

Can you try (not for production, just as a local test!) updating your `Gemfile` to point to:

```ruby
gem 'rapporteur', git: 'https://github.com/envylabs/rapporteur.git', ref: 'engine-updates'
```

Update your `config/routes.rb` with:

```ruby
Rails.application.routes.draw do
  mount Rapporteur::Engine, at: '/status'
end
```

Then doing a `bundle install`. And anywhere you might've (although I doubt you were) been referencing `status_path` or `status_url` route generators in your Templates, you'll need to update those to be `rapporteur.status_path(format: 'json')`.

**Comment by nbibler** [comment]
@sshaw Get a chance to try? If so... how'd it go?

**Comment by nbibler** [comment]
I'm assuming this worked and have merged the changes into the master branch.

**Comment by sshaw** [comment]
Hi, sorry for the late reply. 

Getting the following error under Rails 4.1.16:

```
/Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/rapporteur-3.5.0/config/routes.rb:5:in `block in <top (required)>': undefined method `app' for #<Sprockets::Environment:0x007fd6f9c18ef0> (NoMethodError)
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/actionpack-4.1.16/lib/action_dispatch/journey/routes.rb:32:in `each'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/actionpack-4.1.16/lib/action_dispatch/journey/routes.rb:32:in `each'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/rapporteur-3.5.0/config/routes.rb:5:in `any?'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/rapporteur-3.5.0/config/routes.rb:5:in `<top (required)>'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:241:in `load'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:241:in `block in load'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:241:in `load'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/activesupport-4.1.16/lib/active_support/file_update_checker.rb:75:in `execute'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/application/finisher.rb:71:in `block in <module:Finisher>'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/initializable.rb:30:in `run'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/skyes/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/skyes/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/skyes/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/skyes/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/skyes/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/skyes/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/skyes/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/skyes/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/skyes/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/application.rb:300:in `initialize!'
	from /Users/skyes/code/ruby/rails41-test/config/environment.rb:5:in `<top (required)>'
	from /Users/skyes/code/ruby/rails41-test/config.ru:3:in `require'
	from /Users/skyes/code/ruby/rails41-test/config.ru:3:in `block in <main>'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
	from /Users/skyes/code/ruby/rails41-test/config.ru:in `new'
	from /Users/skyes/code/ruby/rails41-test/config.ru:in `<main>'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/rack-1.5.5/lib/rack/builder.rb:49:in `eval'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/rack-1.5.5/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/rack-1.5.5/lib/rack/builder.rb:40:in `parse_file'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/rack-1.5.5/lib/rack/server.rb:277:in `build_app_and_options_from_config'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/rack-1.5.5/lib/rack/server.rb:199:in `app'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/commands/server.rb:50:in `app'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/rack-1.5.5/lib/rack/server.rb:314:in `wrapped_app'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/commands/server.rb:130:in `log_to_stdout'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/commands/server.rb:67:in `start'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:81:in `block in server'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/skyes/.rvm/gems/ruby-2.3.0@rails41/gems/railties-4.1.16/lib/rails/commands.rb:17:in `<top (required)>'
	from ./bin/rails:4:in `require'
	from ./bin/rails:4:in `<main>'
```

**Comment by nbibler** [comment]
Hmm.. ok. I'll take a look when I can and get back with you. In the meantime, I'm going to move this to a new ticket (#15).
